In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

In [25]:
dataset = pd.read_csv('far.csv')
dataset.head()

Class      FA Card         Description Major Category IHS Categorization  \
0    TW  FA/TW280629  Cooling System IPT          TOWER    Air Conditioner   
1    TW  FA/TW203086   2HP LG Split Unit          TOWER    Air Conditioner   
2    TW  FA/TW255751  2HP WINDOW UNIT AC          TOWER    Air Conditioner   
3    TW  FA/TW255760  2HP WINDOW UNIT AC          TOWER    Air Conditioner   
4    TW  FA/TW203087   2HP LG Split Unit          TOWER    Air Conditioner   

  My Categorization  Parent  Sub-FA Card      Bar Code Status  ...  \
0   Air Conditioner  Parent  FA/TW280629  9.000660e+09      F  ...   
1   Air Conditioner  Parent          NaN  9.000418e+09      F  ...   
2   Air Conditioner  Parent          NaN  9.000418e+09      F  ...   
3   Air Conditioner  Parent          NaN  9.000418e+09      F  ...   
4   Air Conditioner  Parent          NaN  9.000418e+09      F  ...   

  Disposal in Period Acquisition Cost 31/07/18 Depreciation 31/12/17  \
0                  0                799,313.00           -197,608.00   
1                  0                380,364.72            -50,136.00   
2                  0                180,931.58            -65,338.00   
3                  0                180,931.58            -65,338.00   
4                  0                149,583.47            -50,136.00   

  Depreciation in Period Disposal Depreciation in Period  \
0            -155,421.00                               0   
1            -220,277.00                               0   
2             -35,182.00                               0   
3             -35,182.00                               0   
4             -35,280.00                               0   

  Depreciation 31/07/18 Book Value 31/12/17 Book Value 31/07/18  \
0           -353,029.00          601,705.00          446,284.00   
1           -270,413.00           25,072.47          109,951.72   
2           -100,520.00          115,593.58           80,411.58   
3           -100,520.00          115,593.58           80,411.58   
4            -85,416.00           25,072.47           64,167.47   

  Dep. Start date Useful life  
0        4/4/2017         3.0  
1        1/1/2016         3.0  
2       12/1/2016         3.0  
3       12/1/2016         3.0  
4        1/1/2016         3.0  

[5 rows x 25 columns]

In [3]:
dataset.Status.unique()

array(['F', 'NF', nan], dtype=object)

In [4]:
dataset.drop(['Remarks', 'Sub-FA Card', 'Bar Code', 'Status'], axis=1, inplace=True)

In [5]:
dataset.Parent.fillna('Not a Number', inplace = True)
dataset.isnull().sum()

Class                              0
FA Card                            0
Description                        0
Major Category                     0
IHS Categorization                 0
My Categorization                  0
Parent                             0
Site New Code                      0
Alternate Site ID                  0
Acquisition Cost 31/12/17          0
Addition in Period                 0
Disposal in Period                 0
Acquisition Cost 31/07/18          0
Depreciation 31/12/17              0
Depreciation in Period             0
Disposal Depreciation in Period    0
Depreciation 31/07/18              0
Book Value 31/12/17                0
Book Value 31/07/18                0
Dep. Start date                    0
Useful life                        0
dtype: int64

In [6]:
dataset = dataset.drop('Class', axis=1)
dataset.head()

FA Card         Description Major Category IHS Categorization  \
0  FA/TW280629  Cooling System IPT          TOWER    Air Conditioner   
1  FA/TW203086   2HP LG Split Unit          TOWER    Air Conditioner   
2  FA/TW255751  2HP WINDOW UNIT AC          TOWER    Air Conditioner   
3  FA/TW255760  2HP WINDOW UNIT AC          TOWER    Air Conditioner   
4  FA/TW203087   2HP LG Split Unit          TOWER    Air Conditioner   

  My Categorization  Parent Site New Code Alternate Site ID  \
0   Air Conditioner  Parent  IHS_OND_863A     IHS_OND_0863A   
1   Air Conditioner  Parent  IHS_OND_878A     IHS_OND_0878A   
2   Air Conditioner  Parent  IHS_OND_885A     IHS_OND_0885A   
3   Air Conditioner  Parent  IHS_OND_885A     IHS_OND_0885A   
4   Air Conditioner  Parent  IHS_OND_878A     IHS_OND_0878A   

  Acquisition Cost 31/12/17 Addition in Period Disposal in Period  \
0                799,313.00                  0                  0   
1                 75,208.47         305,156.25                  0   
2                180,931.58                  0                  0   
3                180,931.58                  0                  0   
4                 75,208.47          74,375.00                  0   

  Acquisition Cost 31/07/18 Depreciation 31/12/17 Depreciation in Period  \
0                799,313.00           -197,608.00            -155,421.00   
1                380,364.72            -50,136.00            -220,277.00   
2                180,931.58            -65,338.00             -35,182.00   
3                180,931.58            -65,338.00             -35,182.00   
4                149,583.47            -50,136.00             -35,280.00   

  Disposal Depreciation in Period Depreciation 31/07/18 Book Value 31/12/17  \
0                               0           -353,029.00          601,705.00   
1                               0           -270,413.00           25,072.47   
2                               0           -100,520.00          115,593.58   
3                               0           -100,520.00          115,593.58   
4                               0            -85,416.00           25,072.47   

  Book Value 31/07/18 Dep. Start date  Useful life  
0          446,284.00        4/4/2017          3.0  
1          109,951.72        1/1/2016          3.0  
2           80,411.58       12/1/2016          3.0  
3           80,411.58       12/1/2016          3.0  
4           64,167.47        1/1/2016          3.0

In [7]:
X = dataset.drop('Parent', axis=1)
y = dataset.iloc[:, 5]

In [8]:
#label encoding categorical variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
obj_cols = X.columns[X.dtypes == object]
for i in obj_cols:
    X[i] = le.fit_transform(X[i].astype(str))

y_le = LabelEncoder()
y = y_le.fit_transform(y)

In [9]:
pd.concat([dataset.Parent, pd.Series(y)], axis=1, join='inner', keys=['Paret', 'Code']).head()

Paret  Code
0  Parent     2
1  Parent     2
2  Parent     2
3  Parent     2
4  Parent     2

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

In [11]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [12]:
y_pred = classifier.predict(X_test)

y_pred = y_le.inverse_transform(y_pred)
y_test = y_le.inverse_transform(y_test)

In [13]:
result = pd.concat([pd.Series(y_test), pd.Series(y_pred)], axis=1,join = 'inner', keys=['y_test', 'y_pred'])

In [14]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[29  2  9]
 [ 3 58  0]
 [13  1 85]]


In [15]:
result.to_csv('result.csv')

### TESTING THE MODEL

In [16]:
test = pd.read_csv('test set.csv')
test.drop(['Class','Remarks', 'Sub-FA Card', 'Bar Code', 'Status'], axis=1, inplace=True)

test.head()

FA Card         Description Major Category IHS Categorization  \
0  FA/TW280629  Cooling System IPT          TOWER    Air Conditioner   
1  FA/TW203086   2HP LG Split Unit          TOWER    Air Conditioner   
2  FA/TW255751  2HP WINDOW UNIT AC          TOWER    Air Conditioner   
3  FA/TW255760  2HP WINDOW UNIT AC          TOWER    Air Conditioner   
4  FA/TW203087   2HP LG Split Unit          TOWER    Air Conditioner   

  My Categorization  Parent Site New Code Alternate Site ID  \
0   Air Conditioner  Parent  IHS_OND_863A     IHS_OND_0863A   
1   Air Conditioner  Parent  IHS_OND_878A     IHS_OND_0878A   
2   Air Conditioner  Parent  IHS_OND_885A     IHS_OND_0885A   
3   Air Conditioner  Parent  IHS_OND_885A     IHS_OND_0885A   
4   Air Conditioner  Parent  IHS_OND_878A     IHS_OND_0878A   

  Acquisition Cost 31/12/17 Addition in Period Disposal in Period  \
0                799,313.00                  0                  0   
1                 75,208.47         305,156.25                  0   
2                180,931.58                  0                  0   
3                180,931.58                  0                  0   
4                 75,208.47          74,375.00                  0   

  Acquisition Cost 31/07/18 Depreciation 31/12/17 Depreciation in Period  \
0                799,313.00           -197,608.00            -155,421.00   
1                380,364.72            -50,136.00            -220,277.00   
2                180,931.58            -65,338.00             -35,182.00   
3                180,931.58            -65,338.00             -35,182.00   
4                149,583.47            -50,136.00             -35,280.00   

  Disposal Depreciation in Period Depreciation 31/07/18 Book Value 31/12/17  \
0                               0           -353,029.00          601,705.00   
1                               0           -270,413.00           25,072.47   
2                               0           -100,520.00          115,593.58   
3                               0           -100,520.00          115,593.58   
4                               0            -85,416.00           25,072.47   

  Book Value 31/07/18 Dep. Start date  Useful life  
0          446,284.00        4/4/2017          3.0  
1          109,951.72        1/1/2016          3.0  
2           80,411.58       12/1/2016          3.0  
3           80,411.58       12/1/2016          3.0  
4           64,167.47        1/1/2016          3.0

In [17]:
ind_test = test.drop('Parent', axis=1)
dep_test = test.iloc[:, 5]
#label encoding categorical variables
from sklearn.preprocessing import LabelEncoder
le_new = LabelEncoder()
obj_cols = ind_test.columns[ind_test.dtypes == object]
for i in obj_cols:
    ind_test[i] = le.fit_transform(ind_test[i].astype(str))

    
dep_test.fillna('Not a Number', inplace = True)

y_le = LabelEncoder()
dep_test = y_le.fit_transform(dep_test)



In [18]:
test_pred = classifier.predict(ind_test)


In [19]:
# Making the Confusion Matrix
new_cm = confusion_matrix(dep_test, test_pred)
print(new_cm)

[[148   2   9]
 [  4 282   0]
 [ 16   1 538]]


In [20]:
test_pred = y_le.inverse_transform(test_pred)


In [21]:
new_result = pd.concat([pd.Series(dep_test), pd.Series(test_pred)], axis=1,join = 'inner', keys=['y_test', 'y_pred'])
new_result.to_csv('new_test_result.csv')